### PR TITLE
fix bad PEiD sigs

### PR DESCRIPTION
**Pull request by wesinator**
remove bad sigs (https://www.zscaler.com/blogs/security-research/your-windows-8-packed)
rename db file to .ini (is in .ini format)
bump version

### CODE REVIEW

**Review by dhondta — COMMENTED** [review]
Hi @wesinator !
Thank you for this contribution.
Can you justify on the removal of these signatures ? How did you determine these are bad ?

**Review by dhondta — COMMENTED** [review]
Hi @wesinator !
As far as I know, an INI file has distinct sections that contains distinct parameters. While this is not enforced, I must mention that the present file contains items with the same sets of parameters, which is a different idea from Windows INI.
Therefore, I don't think this is a valuable addition. Moreover, the fact that it is named `userdb.TXT` is inspired by the original PEiD and its custom signatures database.
Can you revert this back, please ?

**Comment by wesinator** [comment]
1. the sigs that were removed are known false positives that match on
2.  link I provided

**Comment by wesinator** [comment]
1. the sigs that were removed are known false positives that match on any Windows C++ compiled executables
see link I provided https://www.zscaler.com/blogs/security-research/your-windows-8-packed
2.  The standard peid like this one is in a .ini format, I changed it to ini to use syntax highlighting when opened, etc.

**Comment by wesinator** [comment]
@dhondta ok I did revert the .ini changes and just kept the sig change for this PR, since those are two separate changes.

**Comment by dhondta** [comment]
@wesinator Thank you for your contribution !
I just deployed `peid` 1.2.7 on PyPi.

**Pull request merged**
